
services:
  api:
    build: .
    container_name: jwt-api
    ports:
      - '3001:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/jwt-auth
      - JWT_SECRET=supersecretjwt
      - PORT=3000
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: jwt-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
